#!/usr/bin/env bash

# 'gitrepocheck'. Check GIT repositories for changed stuff.
# Copyright © 2015-2021 Mathias Bocquet <mbocquet@sekoya.org>

while getopts ":h:p:s:" opts
do
  case $opts in
    p)
        PATHTOCHECK="$OPTARG"
        ;;
    s)
        SKIP="$OPTARG"
        ;;
    \?|*|h)
        printf "Usage : $(basename $0) [ -p <path>] [-s <skiped dir>]\n"
        exit 0
        ;;
  esac
done

# Create a temporary file with this script name as prefix
TMPFILE="$(mktemp --suffix=-$(basename $0))"

find ${PATHTOCHECK} -xdev -name .git 2>/dev/null|while read REPO
do
    # Strip '/.git' part of the REPO
    DIR="$(dirname ${REPO})"
    # Do the action if $SKIP is empty or if $DIR doesn't contains $SKIP
    if [ -z "${SKIP}" ] || ! [[ "${DIR}" =~ "${SKIP}" ]]
    then
        git --git-dir="${REPO}" --work-tree="${DIR}" status -bs > ${TMPFILE}
        # output only if it has more than one line or contains [ahead|behind|... number]
        if [ $(wc -l < ${TMPFILE}) -gt 1 ] || grep -q \\[.*\\] ${TMPFILE}
        then
            printf "${DIR} "
            cat ${TMPFILE}
            printf "\n"
        fi
        >${TMPFILE}
    fi
done

rm ${TMPFILE}
